services:
    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: "P@55w0rd"
            ACCEPT_EULA: "Y"
        # volumes:
        #   - './Legitarsasagok-MsSql-data:/var/opt/mssql/data:rw'
        ports:
            - "1433:1433"
